second iteration of fixes, making it a bit cleaner
thelostt/ricing pull request #5
Opened 2016-10-13 10:15 UTC by venam

2016-10-13 15:39 UTC, feroldi commented on README.md
> +* This book is on how to understand the parts of your system,
isn't this strange to read?

2016-10-13 15:41 UTC, thelostt commented on README.md
> +out of using it. Learning to serpentine your way through them will reveal
I don't agree on the use of neat words here. The more this book uses simpler words, the more understandable it becomes.

2016-10-13 15:44 UTC, feroldi requested changes
The fixes are okay, but consider using simpler words and simpler sentences.

2016-10-24 04:05 UTC, venam commented on README.md
> +* This book is on how to understand the parts of your system,
You're right on that one.

2016-10-24 04:06 UTC, venam commented on README.md
> +out of using it. Learning to serpentine your way through them will reveal
Swap "serpentine" by "find" and it's good to go.

2016-10-25 09:44 UTC, venam commented
This should do it now.

2016-10-25 12:48 UTC, thelostt commented
okay, i'll be pulling by the time i get to my machine, thanks.

2016-10-27 03:29 UTC, merged